FROM python:3.9-slim

EXPOSE 8501

ENV PYTHONUNBUFFERED=1


RUN apt-get update && apt-get install -y \
    build-essential \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache --upgrade pip setuptools

RUN git clone

WORKDIR fever-challenge/src/app

RUN pip3 install -r requirements.txt

RUN echo "!!!! If the address below doesn't work try localhost !!!!!!"

ENTRYPOINT ["streamlit", "run", "streamlit__app.py", "--server.port=8501", "--server.address=0.0.0.0"]